/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as WaitRouteImport } from './routes/wait'
import { Route as CoursesIndexRouteImport } from './routes/courses/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as CoursesCourseIdIndexRouteImport } from './routes/courses/$courseId/index'
import { Route as CoursesCourseIdGraphRouteImport } from './routes/courses/$courseId/graph'
import { Route as SessionTextbookCurriculumNodeIdRouteImport } from './routes/session/textbook/$curriculumNodeId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const WaitRoute = WaitRouteImport.update({
  id: '/wait',
  path: '/wait',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesIndexRoute = CoursesIndexRouteImport.update({
  id: '/courses/',
  path: '/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdIndexRoute = CoursesCourseIdIndexRouteImport.update({
  id: '/courses/$courseId/',
  path: '/courses/$courseId/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesCourseIdGraphRoute = CoursesCourseIdGraphRouteImport.update({
  id: '/courses/$courseId/graph',
  path: '/courses/$courseId/graph',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionTextbookCurriculumNodeIdRoute =
  SessionTextbookCurriculumNodeIdRouteImport.update({
    id: '/session/textbook/$curriculumNodeId',
    path: '/session/textbook/$curriculumNodeId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/wait': typeof WaitRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$courseId/graph': typeof CoursesCourseIdGraphRoute
  '/session/textbook/$curriculumNodeId': typeof SessionTextbookCurriculumNodeIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/wait': typeof WaitRoute
  '/courses': typeof CoursesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$courseId/graph': typeof CoursesCourseIdGraphRoute
  '/session/textbook/$curriculumNodeId': typeof SessionTextbookCurriculumNodeIdRoute
  '/courses/$courseId': typeof CoursesCourseIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/wait': typeof WaitRoute
  '/courses/': typeof CoursesIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/courses/$courseId/graph': typeof CoursesCourseIdGraphRoute
  '/session/textbook/$curriculumNodeId': typeof SessionTextbookCurriculumNodeIdRoute
  '/courses/$courseId/': typeof CoursesCourseIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/wait'
    | '/courses/'
    | '/api/auth/$'
    | '/courses/$courseId/graph'
    | '/session/textbook/$curriculumNodeId'
    | '/courses/$courseId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/wait'
    | '/courses'
    | '/api/auth/$'
    | '/courses/$courseId/graph'
    | '/session/textbook/$curriculumNodeId'
    | '/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/wait'
    | '/courses/'
    | '/api/auth/$'
    | '/courses/$courseId/graph'
    | '/session/textbook/$curriculumNodeId'
    | '/courses/$courseId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  WaitRoute: typeof WaitRoute
  CoursesIndexRoute: typeof CoursesIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  CoursesCourseIdGraphRoute: typeof CoursesCourseIdGraphRoute
  SessionTextbookCurriculumNodeIdRoute: typeof SessionTextbookCurriculumNodeIdRoute
  CoursesCourseIdIndexRoute: typeof CoursesCourseIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wait': {
      id: '/wait'
      path: '/wait'
      fullPath: '/wait'
      preLoaderRoute: typeof WaitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/': {
      id: '/courses/'
      path: '/courses'
      fullPath: '/courses/'
      preLoaderRoute: typeof CoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/': {
      id: '/courses/$courseId/'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId/'
      preLoaderRoute: typeof CoursesCourseIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses/$courseId/graph': {
      id: '/courses/$courseId/graph'
      path: '/courses/$courseId/graph'
      fullPath: '/courses/$courseId/graph'
      preLoaderRoute: typeof CoursesCourseIdGraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session/textbook/$curriculumNodeId': {
      id: '/session/textbook/$curriculumNodeId'
      path: '/session/textbook/$curriculumNodeId'
      fullPath: '/session/textbook/$curriculumNodeId'
      preLoaderRoute: typeof SessionTextbookCurriculumNodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  WaitRoute: WaitRoute,
  CoursesIndexRoute: CoursesIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  CoursesCourseIdGraphRoute: CoursesCourseIdGraphRoute,
  SessionTextbookCurriculumNodeIdRoute: SessionTextbookCurriculumNodeIdRoute,
  CoursesCourseIdIndexRoute: CoursesCourseIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
